server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: todoapp
            uri: lb://todoapp
            predicates: Path=/todoapp/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/